local info = {
    Name = 'Layer',
    ctype = 'GameLayerObjectData',
    Size = { X = 820.000000, Y = 580.000000},
    child = {
        {
            ctype = 'PanelObjectData',
            Name = 'Horse',
            Tag = 373 ,
            TouchEnable = true,
            LeftMargin = -1.428500,
            RightMargin = 1.428500,
            Position = { x = -1, y = 0},
            Scale = { x = 1.000000, y = 1.000000},
            AnchorPoint = { x = 0, y = 0},
            Size = { x = 820.000000, y = 580.000000},
            PrePosition = { x = -0.001800, y = 0.000000},
            PreSize = { x = 1.000000, y = 1.000000},
            ComboBoxIndex = 1 ,
            BackColorAlpha = 0 ,
            SingleColor = {r = 150, g = 200, b = 255},
            FirstColor = {r = 150, g = 200, b = 255},
            ColorVector = { x = 0.000000, y = 1.000000},
            child = {
                {
                    ctype = 'PanelObjectData',
                    Name = 'P_Top_Left',
                    Tag = 94 ,
                    TouchEnable = true,
                    LeftMargin = 8.000000,
                    RightMargin = 402.000000,
                    BottomMargin = 280.000000,
                    Position = { x = 8, y = 280},
                    Scale = { x = 1.000000, y = 1.000000},
                    AnchorPoint = { x = 0, y = 0},
                    Size = { x = 390.000000, y = 300.000000},
                    PrePosition = { x = 0.010000, y = 0.482800},
                    PreSize = { x = 0.487500, y = 0.468800},
                    ComboBoxIndex = 1 ,
                    BackColorAlpha = 0 ,
                    SingleColor = {r = 150, g = 200, b = 255},
                    FirstColor = {r = 150, g = 200, b = 255},
                    ColorVector = { x = 0.000000, y = 1.000000},
                    child = {
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_12',
                            Tag = 329 ,
                            TouchEnable = true,
                            LeftMargin = 8.997500,
                            RightMargin = 331.002500,
                            TopMargin = 4.995200,
                            BottomMargin = 245.004800,
                            Position = { x = 33, y = 270},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.087200, y = 0.900000},
                            PreSize = { x = 0.061700, y = 0.078100},
                            Scale9Enable = true,
                            Scale9Width = 64.000000,
                            Scale9Height = 64.000000,
                            ButtonText = '灵丹',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_5_26',
                            Tag = 340 ,
                            TouchEnable = true,
                            LeftMargin = 8.569100,
                            RightMargin = 331.430900,
                            TopMargin = 64.573100,
                            BottomMargin = 185.426900,
                            Position = { x = 33, y = 210},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.086100, y = 0.701400},
                            PreSize = { x = 0.061700, y = 0.078100},
                            Scale9Enable = true,
                            Scale9Width = 64.000000,
                            Scale9Height = 64.000000,
                            ButtonText = '仙丹',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_2_14',
                            Tag = 330 ,
                            TouchEnable = true,
                            LeftMargin = 339.981400,
                            RightMargin = 22.018600,
                            TopMargin = 120.005300,
                            BottomMargin = 125.994700,
                            Position = { x = 353, y = 152},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 28.000000, y = 54.000000},
                            PrePosition = { x = 0.907600, y = 0.510000},
                            PreSize = { x = 0.034600, y = 0.084400},
                            Scale9Enable = true,
                            Scale9Width = 28.000000,
                            Scale9Height = 54.000000,
                            FontSize = 14 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_4_16',
                            Tag = 331 ,
                            TouchEnable = true,
                            LeftMargin = 18.204100,
                            RightMargin = 343.795900,
                            TopMargin = 120.005300,
                            BottomMargin = 125.994700,
                            Position = { x = 32, y = 152},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 28.000000, y = 54.000000},
                            PrePosition = { x = 0.082600, y = 0.510000},
                            PreSize = { x = 0.034600, y = 0.084400},
                            Scale9Enable = true,
                            Scale9Width = 28.000000,
                            Scale9Height = 54.000000,
                            FontSize = 14 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_40',
                            Tag = 332 ,
                            TouchEnable = true,
                            LeftMargin = 9.717000,
                            RightMargin = 330.283000,
                            TopMargin = 180.652900,
                            BottomMargin = 69.347100,
                            Position = { x = 34, y = 94},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.089000, y = 0.314500},
                            PreSize = { x = 0.061700, y = 0.078100},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_42',
                            Tag = 333 ,
                            TouchEnable = true,
                            LeftMargin = 9.111500,
                            RightMargin = 330.888500,
                            TopMargin = 239.070400,
                            BottomMargin = 10.929600,
                            Position = { x = 34, y = 35},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.087500, y = 0.119800},
                            PreSize = { x = 0.061700, y = 0.078100},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_1_44',
                            Tag = 334 ,
                            TouchEnable = true,
                            LeftMargin = 328.587900,
                            RightMargin = 11.412100,
                            TopMargin = 243.070800,
                            BottomMargin = 6.929200,
                            Position = { x = 353, y = 31},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.906600, y = 0.106400},
                            PreSize = { x = 0.061700, y = 0.078100},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_2_46',
                            Tag = 335 ,
                            TouchEnable = true,
                            LeftMargin = 329.528100,
                            RightMargin = 10.471900,
                            TopMargin = 180.648000,
                            BottomMargin = 69.352000,
                            Position = { x = 354, y = 94},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 50.000000, y = 50.000000},
                            PrePosition = { x = 0.909000, y = 0.314500},
                            PreSize = { x = 0.061700, y = 0.078100},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_18',
                            Tag = 336 ,
                            TouchEnable = true,
                            LeftMargin = 92.998500,
                            RightMargin = 197.001500,
                            TopMargin = 241.799900,
                            BottomMargin = 8.200100,
                            Position = { x = 142, y = 33},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 50.000000},
                            PrePosition = { x = 0.366700, y = 0.110700},
                            PreSize = { x = 0.123500, y = 0.078100},
                            Scale9Enable = true,
                            Scale9Width = 136.000000,
                            Scale9Height = 49.000000,
                            ButtonText = '骑乘',
                            FontSize = 24 ,
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_20',
                            Tag = 337 ,
                            TouchEnable = true,
                            LeftMargin = 207.142400,
                            RightMargin = 82.857600,
                            TopMargin = 241.448500,
                            BottomMargin = 8.551500,
                            Position = { x = 257, y = 33},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 50.000000},
                            PrePosition = { x = 0.659300, y = 0.111800},
                            PreSize = { x = 0.123500, y = 0.078100},
                            Scale9Enable = true,
                            Scale9Width = 136.000000,
                            Scale9Height = 49.000000,
                            ButtonText = '幻化',
                            FontSize = 24 ,
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                        },
                    },
                },
                {
                    ctype = 'PanelObjectData',
                    Name = 'P_Top_Right',
                    Tag = 95 ,
                    TouchEnable = true,
                    LeftMargin = 404.190000,
                    RightMargin = 5.810000,
                    BottomMargin = 280.000000,
                    Position = { x = 404, y = 280},
                    Scale = { x = 1.000000, y = 1.000000},
                    AnchorPoint = { x = 0, y = 0},
                    Size = { x = 390.000000, y = 300.000000},
                    PrePosition = { x = 0.505200, y = 0.482800},
                    PreSize = { x = 0.487500, y = 0.468800},
                    ComboBoxIndex = 1 ,
                    BackColorAlpha = 0 ,
                    SingleColor = {r = 150, g = 200, b = 255},
                    FirstColor = {r = 150, g = 200, b = 255},
                    ColorVector = { x = 0.000000, y = 1.000000},
                    child = {
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_5_34',
                            Tag = 350 ,
                            LeftMargin = 61.852500,
                            RightMargin = 58.147500,
                            TopMargin = 4.895800,
                            BottomMargin = 259.104200,
                            Position = { x = 196, y = 277},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 270.000000, y = 36.000000},
                            PrePosition = { x = 0.504700, y = 0.923700},
                            LabelText = '战斗力：9899999',
                            FontSize = 36 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_36',
                            Tag = 351 ,
                            LeftMargin = 88.014600,
                            RightMargin = 201.985400,
                            TopMargin = 46.709400,
                            BottomMargin = 233.290600,
                            Position = { x = 138, y = 243},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.353900, y = 0.811000},
                            LabelText = '物攻:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_0_38',
                            Tag = 352 ,
                            LeftMargin = 85.518300,
                            RightMargin = 204.481700,
                            TopMargin = 271.719200,
                            BottomMargin = 8.280800,
                            Position = { x = 135, y = 18},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.347500, y = 0.060900},
                            LabelText = '法免:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_2_40',
                            Tag = 353 ,
                            LeftMargin = 88.260000,
                            RightMargin = 201.740000,
                            TopMargin = 72.517400,
                            BottomMargin = 207.482600,
                            Position = { x = 138, y = 217},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.354500, y = 0.724900},
                            LabelText = '物防:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_3_42',
                            Tag = 354 ,
                            LeftMargin = 85.325400,
                            RightMargin = 204.674600,
                            TopMargin = 242.472000,
                            BottomMargin = 37.528000,
                            Position = { x = 135, y = 47},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.347000, y = 0.158400},
                            LabelText = '物免:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_4_44',
                            Tag = 355 ,
                            LeftMargin = 86.653600,
                            RightMargin = 203.346400,
                            TopMargin = 99.730700,
                            BottomMargin = 180.269300,
                            Position = { x = 136, y = 190},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.350400, y = 0.634200},
                            LabelText = '法防:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_5_46',
                            Tag = 356 ,
                            LeftMargin = 88.539600,
                            RightMargin = 201.460400,
                            TopMargin = 156.116500,
                            BottomMargin = 123.883500,
                            Position = { x = 138, y = 133},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.355200, y = 0.446300},
                            LabelText = '抗暴:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_6_48',
                            Tag = 357 ,
                            LeftMargin = 86.381300,
                            RightMargin = 203.618700,
                            TopMargin = 126.819000,
                            BottomMargin = 153.181000,
                            Position = { x = 136, y = 163},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.349700, y = 0.543900},
                            LabelText = '暴击:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_7_50',
                            Tag = 358 ,
                            LeftMargin = 87.314000,
                            RightMargin = 202.686000,
                            TopMargin = 213.742100,
                            BottomMargin = 66.257900,
                            Position = { x = 137, y = 76},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.352100, y = 0.254200},
                            LabelText = '闪避:99999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_6_8_52',
                            Tag = 359 ,
                            LeftMargin = 86.820800,
                            RightMargin = 203.179200,
                            TopMargin = 184.164400,
                            BottomMargin = 95.835600,
                            Position = { x = 136, y = 105},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.350800, y = 0.352800},
                            LabelText = '命中:99999',
                            FontSize = 20 ,
                        },
                    },
                },
                {
                    ctype = 'PanelObjectData',
                    Name = 'P_Center',
                    Tag = 96 ,
                    TouchEnable = true,
                    LeftMargin = 7.999700,
                    RightMargin = 7.000300,
                    TopMargin = 302.618600,
                    BottomMargin = 197.381400,
                    Position = { x = 7, y = 197},
                    Scale = { x = 1.000000, y = 1.000000},
                    AnchorPoint = { x = 0, y = 0},
                    Size = { x = 785.000000, y = 80.000000},
                    PrePosition = { x = 0.010000, y = 0.340300},
                    PreSize = { x = 0.981200, y = 0.125000},
                    ComboBoxIndex = 1 ,
                    BackColorAlpha = 0 ,
                    SingleColor = {r = 150, g = 200, b = 255},
                    FirstColor = {r = 150, g = 200, b = 255},
                    ColorVector = { x = 0.000000, y = 1.000000},
                    child = {
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_48',
                            Tag = 341 ,
                            TouchEnable = true,
                            LeftMargin = 5.142300,
                            RightMargin = 699.857700,
                            TopMargin = 1.000100,
                            BottomMargin = -1.000100,
                            Position = { x = 45, y = 38},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.057500, y = 0.487500},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_0_50',
                            Tag = 342 ,
                            TouchEnable = true,
                            LeftMargin = 92.285200,
                            RightMargin = 612.714800,
                            TopMargin = 1.001000,
                            BottomMargin = -1.001000,
                            Position = { x = 132, y = 38},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.168500, y = 0.487500},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_1_52',
                            Tag = 343 ,
                            TouchEnable = true,
                            LeftMargin = 265.857200,
                            RightMargin = 439.142800,
                            TopMargin = 1.143100,
                            BottomMargin = -1.143100,
                            Position = { x = 305, y = 38},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.389600, y = 0.485700},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_2_54',
                            Tag = 344 ,
                            TouchEnable = true,
                            LeftMargin = 176.998800,
                            RightMargin = 528.001200,
                            TopMargin = 0.857800,
                            BottomMargin = -0.857800,
                            Position = { x = 216, y = 39},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.276400, y = 0.489300},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_3_56',
                            Tag = 345 ,
                            TouchEnable = true,
                            LeftMargin = 351.859000,
                            RightMargin = 353.141000,
                            TopMargin = 0.715100,
                            BottomMargin = -0.715100,
                            Position = { x = 391, y = 39},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.499200, y = 0.491100},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_4_58',
                            Tag = 346 ,
                            TouchEnable = true,
                            LeftMargin = 442.572500,
                            RightMargin = 262.427500,
                            TopMargin = 1.429200,
                            BottomMargin = -1.429200,
                            Position = { x = 482, y = 38},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.614700, y = 0.482100},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_5_60',
                            Tag = 347 ,
                            TouchEnable = true,
                            LeftMargin = 533.715100,
                            RightMargin = 171.284900,
                            TopMargin = 0.858000,
                            BottomMargin = -0.858000,
                            Position = { x = 573, y = 39},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.730800, y = 0.489300},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_6_62',
                            Tag = 348 ,
                            TouchEnable = true,
                            LeftMargin = 618.146200,
                            RightMargin = 86.853800,
                            TopMargin = 0.715400,
                            BottomMargin = -0.715400,
                            Position = { x = 658, y = 39},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.838400, y = 0.491100},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ImageViewObjectData',
                            Name = 'Image_2_0_0_7_64',
                            Tag = 349 ,
                            TouchEnable = true,
                            LeftMargin = 701.719600,
                            RightMargin = 3.280400,
                            TopMargin = 1.000700,
                            BottomMargin = -1.000700,
                            Position = { x = 741, y = 38},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.944900, y = 0.487500},
                            PreSize = { x = 0.098800, y = 0.125000},
                            FileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                    },
                },
                {
                    ctype = 'PanelObjectData',
                    Name = 'P_Botton',
                    Tag = 97 ,
                    TouchEnable = true,
                    LeftMargin = 8.000000,
                    RightMargin = 7.000000,
                    TopMargin = 388.952300,
                    BottomMargin = 11.047700,
                    Position = { x = 8, y = 11},
                    Scale = { x = 1.000000, y = 1.000000},
                    AnchorPoint = { x = 0, y = 0},
                    Size = { x = 785.000000, y = 180.000000},
                    PrePosition = { x = 0.010000, y = 0.019000},
                    PreSize = { x = 0.981200, y = 0.281300},
                    ComboBoxIndex = 1 ,
                    BackColorAlpha = 0 ,
                    SingleColor = {r = 150, g = 200, b = 255},
                    FirstColor = {r = 150, g = 200, b = 255},
                    ColorVector = { x = 0.000000, y = 1.000000},
                    child = {
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_17_54',
                            Tag = 360 ,
                            LeftMargin = 562.458500,
                            RightMargin = -7.458500,
                            TopMargin = 1.410000,
                            BottomMargin = 158.590000,
                            Position = { x = 677, y = 168},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 230.000000, y = 20.000000},
                            PrePosition = { x = 0.863000, y = 0.936600},
                            LabelText = '消耗：坐骑进化丹（0/2）',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_17_0_56',
                            Tag = 361 ,
                            LeftMargin = 621.891700,
                            RightMargin = 33.108300,
                            TopMargin = 26.714200,
                            BottomMargin = 133.285800,
                            Position = { x = 686, y = 143},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 130.000000, y = 20.000000},
                            PrePosition = { x = 0.875000, y = 0.796000},
                            LabelText = '仙币：9999999',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_17_1_58',
                            Tag = 362 ,
                            LeftMargin = 232.497500,
                            RightMargin = 452.502500,
                            TopMargin = -1.035600,
                            BottomMargin = 161.035600,
                            Position = { x = 282, y = 171},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 100.000000, y = 20.000000},
                            PrePosition = { x = 0.359900, y = 0.950200},
                            LabelText = '进阶祝福值',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'LoadingBarObjectData',
                            Name = 'LoadingBar_2_6',
                            Tag = 363 ,
                            LeftMargin = 27.476800,
                            RightMargin = 237.523200,
                            TopMargin = 23.600600,
                            BottomMargin = 136.399400,
                            Position = { x = 287, y = 146},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            CColor = {r = 91, g = 222, b = 16},
                            Size = { x = 520.000000, y = 20.000000},
                            PrePosition = { x = 0.366200, y = 0.813300},
                            PreSize = { x = 0.642000, y = 0.031300},
                            ProgressInfo = 88 ,
                            ImageFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/Default/LoadingBarFile.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'TextObjectData',
                            Name = 'Text_17_1_0_60',
                            Tag = 364 ,
                            LeftMargin = 146.294600,
                            RightMargin = 298.705400,
                            TopMargin = 61.333800,
                            BottomMargin = 98.666200,
                            Position = { x = 316, y = 108},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 340.000000, y = 20.000000},
                            PrePosition = { x = 0.402900, y = 0.603700},
                            LabelText = '材料不足时自动购买（绑定元宝优先）',
                            FontSize = 20 ,
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_4_0_28',
                            Tag = 365 ,
                            TouchEnable = true,
                            LeftMargin = 14.285200,
                            RightMargin = 742.714800,
                            TopMargin = 105.428600,
                            BottomMargin = 20.571400,
                            Position = { x = 28, y = 47},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 28.000000, y = 54.000000},
                            PrePosition = { x = 0.036000, y = 0.264300},
                            PreSize = { x = 0.034600, y = 0.084400},
                            Scale9Enable = true,
                            Scale9Width = 28.000000,
                            Scale9Height = 54.000000,
                            FontSize = 14 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/left_page_turn_btn_n.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_7_2_0_30',
                            Tag = 366 ,
                            TouchEnable = true,
                            LeftMargin = 517.694900,
                            RightMargin = 239.305100,
                            TopMargin = 108.286900,
                            BottomMargin = 17.713100,
                            Position = { x = 531, y = 44},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 28.000000, y = 54.000000},
                            PrePosition = { x = 0.677300, y = 0.248400},
                            PreSize = { x = 0.034600, y = 0.084400},
                            Scale9Enable = true,
                            Scale9Width = 28.000000,
                            Scale9Height = 54.000000,
                            FontSize = 14 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/right_page_turn_btn_n.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_0_32',
                            Tag = 367 ,
                            TouchEnable = true,
                            LeftMargin = 55.999800,
                            RightMargin = 649.000200,
                            TopMargin = 90.714400,
                            BottomMargin = 9.285600,
                            Position = { x = 95, y = 49},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.122300, y = 0.273800},
                            PreSize = { x = 0.098800, y = 0.125000},
                            Scale9Enable = true,
                            Scale9Width = 62.000000,
                            Scale9Height = 62.000000,
                            FontSize = 24 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_0_0_34',
                            Tag = 368 ,
                            TouchEnable = true,
                            LeftMargin = 145.999500,
                            RightMargin = 559.000500,
                            TopMargin = 91.428700,
                            BottomMargin = 8.571300,
                            Position = { x = 185, y = 48},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.236900, y = 0.269800},
                            PreSize = { x = 0.098800, y = 0.125000},
                            Scale9Enable = true,
                            Scale9Width = 62.000000,
                            Scale9Height = 62.000000,
                            FontSize = 24 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_0_1_36',
                            Tag = 369 ,
                            TouchEnable = true,
                            LeftMargin = 234.570800,
                            RightMargin = 470.429200,
                            TopMargin = 92.285800,
                            BottomMargin = 7.714200,
                            Position = { x = 274, y = 47},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.349800, y = 0.265100},
                            PreSize = { x = 0.098800, y = 0.125000},
                            Scale9Enable = true,
                            Scale9Width = 62.000000,
                            Scale9Height = 62.000000,
                            FontSize = 24 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_0_2_38',
                            Tag = 370 ,
                            TouchEnable = true,
                            LeftMargin = 324.427800,
                            RightMargin = 380.572200,
                            TopMargin = 92.000100,
                            BottomMargin = 7.999900,
                            Position = { x = 364, y = 47},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.464200, y = 0.266700},
                            PreSize = { x = 0.098800, y = 0.125000},
                            Scale9Enable = true,
                            Scale9Width = 62.000000,
                            Scale9Height = 62.000000,
                            FontSize = 24 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_0_3_40',
                            Tag = 371 ,
                            TouchEnable = true,
                            LeftMargin = 418.856700,
                            RightMargin = 286.143300,
                            TopMargin = 90.857300,
                            BottomMargin = 9.142700,
                            Position = { x = 458, y = 49},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 80.000000, y = 80.000000},
                            PrePosition = { x = 0.584500, y = 0.273000},
                            PreSize = { x = 0.098800, y = 0.125000},
                            Scale9Enable = true,
                            Scale9Width = 62.000000,
                            Scale9Height = 62.000000,
                            FontSize = 24 ,
                            TextColor = {r = 65, g = 65, b = 70},
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/user/item_bg01.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'CheckBoxObjectData',
                            Name = 'CheckBox_1_2',
                            Tag = 372 ,
                            TouchEnable = true,
                            LeftMargin = 96.266500,
                            RightMargin = 648.733500,
                            TopMargin = 47.945900,
                            BottomMargin = 92.054100,
                            Position = { x = 116, y = 112},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 40.000000, y = 40.000000},
                            PrePosition = { x = 0.148100, y = 0.622500},
                            CheckedState = true,
                            NormalBackFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            PressedBackFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NodeNormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/Default/CheckBoxNode_Normal.png',
                                Plist = '',
                            },
                            DisableBackFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NodeDisableFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/Default/CheckBoxNode_Disable.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_22',
                            Tag = 338 ,
                            TouchEnable = true,
                            LeftMargin = 620.714600,
                            RightMargin = 14.285400,
                            TopMargin = 51.428400,
                            BottomMargin = 68.571600,
                            Position = { x = 695, y = 98},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 150.000000, y = 60.000000},
                            PrePosition = { x = 0.886300, y = 0.547600},
                            PreSize = { x = 3.000000, y = 1.200000},
                            Scale9Enable = true,
                            Scale9Width = 136.000000,
                            Scale9Height = 49.000000,
                            ButtonText = '进阶',
                            FontSize = 24 ,
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                        },
                        {
                            ctype = 'ButtonObjectData',
                            Name = 'Button_14_0_0_0_24',
                            Tag = 339 ,
                            TouchEnable = true,
                            LeftMargin = 619.463000,
                            RightMargin = 15.537000,
                            TopMargin = 114.202400,
                            BottomMargin = 5.797600,
                            Position = { x = 694, y = 35},
                            Scale = { x = 1.000000, y = 1.000000},
                            AnchorPoint = { x = 0.500000, y = 0.500000},
                            Size = { x = 150.000000, y = 60.000000},
                            PrePosition = { x = 0.884700, y = 0.198900},
                            PreSize = { x = 3.000000, y = 1.200000},
                            Scale9Enable = true,
                            Scale9Width = 136.000000,
                            Scale9Height = 49.000000,
                            ButtonText = '自动进阶',
                            FontSize = 24 ,
                            DisabledFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            PressedFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                            NormalFileData = {
                                Type = 'Normal',
                                Path = 'res/ui/sides_btn.png',
                                Plist = '',
                            },
                        },
                    },
                },
            },
        },
    },
}
function info.create()
    return LayoutLoader:createLayout(info)
 end
return info
