--MainWin.lua
MainWin = simple_class(GUIWindow)

function MainWin:__init()
	print("MainWin:__initself.view=",self.view)
    -- print("MainWin:__init file,param = ",file,param)
    -- local panel_bg = GUIPanel:create9Img("nopack/bg.png")
    -- self:addChild(panel_bg)
    -- print("self.view=",self.view)
    -- self.view:setPosition(200,200)
 --    local parent = GUIImg:create9Img("")
	-- parent.view:setScale9Enabled(true)
	-- parent.view:setCapInsets(cc.rect(10,10,10,10))
 --    self.view:addChild(parent.view)
 	-- local btn = GUIButton:create("ui/common/close.png")
 	-- local btn = GUIButton:create("ui/common/close.png")
	-- local sp = GUIImg:create("ui/common/close.png")
	-- sp:setPosition(200,200)
	-- sp:removeFromParent(true)
	-- btn:setTitleText(winSize.width..","..winSize.height)
	-- btn:setPosition(0,0)
	-- local view_s = self.view:getContentSize()
	-- print("view_s=",view_s.width,view_s.height)
	-- local x,y = self.view:getPosition()
	-- print("view_pos=",x,y)
	-- self.view:addChild(btn.view)
	-- print("self")
	-- print("self.result.panel_1=",self.result.panel_1)
	-- self.view:addChild(self.result.root.view)
	-- self.view:addChild(self.result.panel_1.view)
	-- print("xxxxxxxxxxxxxxxxxxxxself.view=",self.view)
end