--__init.lua

require "SWidget/SWidgetConfig"
require "SWidget/base/SWidgetBase"
require "SWidget/base/STouchBase"
require "SWidget/SButton"
require "SWidget/SLabel"
require "SWidget/SPanel"
require "SWidget/SRadioButtonGroup"
require "SWidget/SImage"
require "SWidget/STextButton"
require "SWidget/SEditBox"
require "SWidget/SRadioButton"
require "SWidget/SImageButton"
require "SWidget/SScroll"
require "SWidget/STextArea"
require "SWidget/SSlotItem"
require "SWidget/SProgress"
require "SWidget/SSwitchBtn"
require "SWidget/SSwitchBtnNew"
require "SWidget/SDragBar"
require "SWidget/STouchPanel"
require "SWidget/VipWidget"
require "SWidget/FightWidget"