--SWidgetConfig.lua
--控件风格定义 配置文件

--字体大小 预设
FONT_MAX_SIZE = 18
FOnt_MID_SIZE = 16
FONT_MIN_SIZE = 14
FONT_DEF_SIZE = FONT_MAX_SIZE

--输入框文字数量限制
EDIT_NUM_MIN = 15
EDIT_NUM_MAX = 30

----对齐方式
ALIGN_DEFAULT =  ALIGN_LEFT
-- ALIGN_LEFT 
-- ALIGN_CENTER
-- ALIGN_RIGHT

----按钮状态
-- CLICK_STATE_UP
-- CLICK_STATE_MOVE
-- CLICK_STATE_DOWN
-- CLICK_STATE_DISABLE

--常用事件类型
-- TOUCH_BEGAN 
-- TOUCH_MOVED
-- TOUCH_ENDED
-- TOUCH_CANCEL
-- TOUCH_CLICK
-- TOUCH_DOUBLE_CLICK,
-- ITEM_DELETE 
-- DRAG_OUT
-- TIMER
-- SCROLL_CREATE_ITEM
-- SCROLL_FINISH_SCROLL
-- KEYBOARD_FINISH_INSERT
-- KEYBOARD_WILL_SHOW
-- KEYBOARD_WILL_HIDE

--scroll类型
-- TYPE_VERTICAL 水平方向
-- TYPE_HORIZONTAL 垂直方向

--label文字方向
--FONT_HORIZONTAL 横   
--FONT_VERTICAL  竖