-- ComAttribute.lua 
-- createed by lyl on 2012-12-28
-- 一些由客户端定义的静态配置

-- 属性名称： 可使用属性的type为下标来取值
-- 炼器布局比较小，有的属性放不下，所以改成两个字
attrNameforForge = {
	        LangGameString[6], -- [6]="未定义属性"
			LangGameString[7], -- [7]="力量"
			LangGameString[8], -- [8]="力量倍率"
			LangGameString[9], -- [9]="身法"
			LangGameString[10], -- [10]="身法倍率"
			LangGameString[11], -- [11]="体魄"
			LangGameString[12], -- [12]="体魄倍率"
			LangGameString[13], -- [13]="聪慧"
			LangGameString[14], -- [14]="聪慧倍率"
			LangGameString[15], -- [15]="精神"
			LangGameString[16], -- [16]="精神倍率"
			LangGameString[17], -- [17]="生命值"
			LangGameString[18], -- [18]="生命值倍率"
			LangGameString[19], -- [19]="内力值"
			LangGameString[20], -- [20]="内力值倍率"
			LangGameString[21], -- [21]="移动速度"
			LangGameString[22], -- [22]="移动速度倍率"
			LangGameString[23], -- [23]="生命"
			LangGameString[23], -- [23]="生命"
			LangGameString[24], -- [24]="内力"
			LangGameString[24], -- [24]="内力"
			LangGameString[25], -- [25]="攻击"
			LangGameString[25], -- [25]="攻击"
			LangGameString[26], -- [26]="物防"
			LangGameString[26], -- [26]="物防"
			LangGameString[27], -- [27]="抗暴击"
			LangGameString[28], -- [28]="暴击几率总和提升"
			LangGameString[25], -- [25]="攻击"
			LangGameString[29], -- [29]="攻击提升"
			LangGameString[30], -- [30]="命中几率"
			LangGameString[31], -- [31]="命中几率总和提升"
			LangGameString[32], -- [32]="法攻"
			LangGameString[32], -- [32]="法攻"
			LangGameString[33], -- [33]="法防"
			LangGameString[33], -- [33]="法防"
			LangGameString[34], -- [34]="暴击"
			LangGameString[34], -- [34]="暴击"
			LangGameString[35], -- [35]="闪避"
			LangGameString[35], -- [35]="闪避"
			LangGameString[36], -- [36]="命中"
			LangGameString[36], -- [36]="命中"
			LangGameString[37], -- [37]="治疗效果"
			LangGameString[38], -- [38]="治疗效果倍率"
			LangGameString[39], -- [39]="生命恢复速度"
			LangGameString[40], -- [40]="生命恢复速度倍率"
			LangGameString[41], -- [41]="内力恢复速度"
			LangGameString[42], -- [42]="内力恢复速度倍率"
			LangGameString[43], -- [43]="攻击速度"
			LangGameString[44], -- [44]="攻击速度倍率"
			LangGameString[45], -- [45]="伤害吸收"
			LangGameString[46], -- [46]="按比例吸收伤害"
			LangGameString[47], -- [47]="伤害"
			LangGameString[48], -- [48]="禁止移动"
			LangGameString[49], -- [49]="晕眩"
			LangGameString[50], -- [50]="禁止使用内攻攻击"
			LangGameString[51], -- [51]="禁止使用外攻攻击"
			LangGameString[52], -- [52]="免疫内攻攻击"
			LangGameString[53], -- [53]="免疫外攻攻击"
			LangGameString[54], -- [54]="免疫各种控制技能"
			LangGameString[55], -- [55]="对目标造成的暴击伤害"
			LangGameString[56], -- [56]="内观暴击伤害比率"
			LangGameString[57], -- [57]="经验值"
			LangGameString[58], -- [58]="活力"
			LangGameString[59], -- [59]="嘲讽"
			LangGameString[60], -- [60]="无敌"
			LangGameString[61], -- [61]="保护状态"
			LangGameString[62], -- [62]="修为恢复速度"
			LangGameString[63], -- [63]="跳跃距离"
			LangGameString[64], -- [64]="定时使用技能"
			LangGameString[65], -- [65]="使用后可隐身$time$秒"
			LangGameString[66], -- [66]="最大修为"
			LangGameString[67], -- [67]="经验增加倍率"
			LangGameString[68], -- [68]="修为值"
			LangGameString[69], -- [69]="杀戮值"
			LangGameString[70], -- [70]="轻功值"
			LangGameString[71], -- [71]="采集体力提高"
			LangGameString[72], -- [72]="杀怪伤害提升"
			LangGameString[73], -- [73]="受到法术伤害"
			LangGameString[74], -- [74]="宠物生命值"
			LangGameString[73], -- [73]="受到法术伤害"
			LangGameString[75], -- [75]="受到物理伤害"
			LangGameString[76], -- [76]="法术伤害反射"
			LangGameString[77], -- [77]="物理伤害反射"
			LangGameString[78], -- [78]="PK保护状态"
			LangGameString[79], -- [79]="忽略物理防御"
			LangGameString[80], -- [80]="忽略法术防御"
			LangGameString[81], -- [81]="攻击伤害追加"
			LangGameString[82], -- [82]="受到暴击几率减少"
			LangGameString[83], -- [83]="受到暴击伤害减少"
			LangGameString[84], -- [84]="历练的增加"
			LangGameString[85], -- [85]="阵营贡献获取速度"
			LangGameString[86], -- [86]="历练的获取速度"
			"",
			""
}

-- 职业名称
_com_attr_job_name = {
	LangGameString[87], -- [87]="天雷" "体术"
    LangGameString[88], -- [88]="蜀山"
    LangGameString[89], -- [89]="圆月" "忍术"
    LangGameString[90], -- [90]="云华" "幻术"
}

-- 性别
_com_attr_sex = {
	LangGameString[91], -- [91]="男"
	LangGameString[92], -- [92]="女"
}

-- 阵营
_com_attr_camp =  {
    LangGameString[93],  -- [93]="逍遥"
    LangGameString[94],  -- [94]="星辰"
    LangGameString[95], -- [95]="逸仙"
}
