-- UIStyle.lua
-- create by hcl on 2014-4-29
-- 定义UI控件的样式

-- ZImageButton样式
UISTYLE_ZIMAGEBUTTON_TWO_WORD = "UISTYLE_ZIMAGEBUTTON_TWO_WORD"			--2个字的红色按钮(ui/common/button2_red.png)
UISTYLE_ZIMAGEBUTTON_THREE_WORD = "UISTYLE_ZIMAGEBUTTON_THREE_WORD";	--3个字的红色按钮(ui/common/tishi_button.png)
UISTYLE_ZIMAGEBUTTON_FOUR_WORD = "UISTYLE_ZIMAGEBUTTON_FOUR_WORD";		--4个字的红色按钮(ui/common/button_red.png)
UISTYLE_ZIMAGEBUTTON_TWO_WORD2 = "UISTYLE_ZIMAGEBUTTON_TWO_WORD2";		--2个字的花纹按钮(ui/common/common_btn4.png)
UISTYLE_ZIMAGEBUTTON_RADIOBTN = "UISTYLE_ZIMAGEBUTTON_RADIOBTN";		--radiobutton使用的样式

UISTYLE_ZBUTTON_MAINWIN = "UISTYLE_ZBUTTON_MAINWIN";					--主界面的按钮
UISTYLE_ZBUTTON_CIRCLE = "UISTYLE_ZBUTTON_CIRCLE";						--圆形按钮			
-- ZTextButton样式
UISTYLE_ZTEXTBUTTON_TWO_WORD = "UISTYLE_ZTEXTBUTTON_TWO_WORD"			--2个字的程序字按钮(ui/common/button2.png)
UISTYLE_ZTEXTBUTTON_THREE_WORD = "UISTYLE_ZTEXTBUTTON_THREE_WORD"		--3个字的程序字按钮(ui/common/button3.png)
UISTYLE_ZTEXTBUTTON_FOUR_WORD = "UISTYLE_ZTEXTBUTTON_FOUR_WORD"			--4个字的程序字按钮(ui/common/button4.png)
UISTYLE_ZTEXTBUTTON_RED_TWO_WORD = "UISTYLE_ZTEXTBUTTON_RED_TWO_WORD"   --2个字的程序字红色按钮(ui/common/button2_red.png)
UISTYLE_ZTEXTBUTTON_MARRIAGE = "UISTYLE_ZTEXTBUTTON_MARRIAGE";					--结婚按钮

-- ZTextCheckBox样式
UISTYLE_ZTEXTCHECKBOX_ONE = "UISTYLE_ZTEXTCHECKBOX_ONE"		--"ui/common/toggle_n.png"
UISTYLE_ZTEXTCHECKBOX_TWO = "UISTYLE_ZTEXTCHECKBOX_TWO"		--"ui/common/common_question_mark.png"
-- ZProgress样式
UISTYLE_ZPROGRESS_ONE = "UISTYLE_ZPROGRESS_ONE"			--ui/common/progress_green.png
UISTYLE_ZPROGRESS_TWO = "UISTYLE_ZPROGRESS_TWO"			--ui/sevenDayAward/process_bar.png
