require "gamecore.config.SceneConfig"
require "gamecore.config.MiniMapConfig"
require "gamecore.config.EntityConfig"
require "gamecore.config.ItemConfig"
require "gamecore.config.SkillConfig"
require "gamecore.config.ActionConfig"
require "gamecore.config.EffectConfig"