LangGameString = {
[1]="充值回馈", 		--../script\config\OpenSerConfig.lua
[2]="修仙初成", 		--../script\config\OpenSerConfig.lua
[3]="战力排行", 		--../script\config\OpenSerConfig.lua
[4]="等级排行", 		--../script\config\OpenSerConfig.lua
[5]="灵根排行", 		--../script\config\OpenSerConfig.lua
[6]="成就排行", 		--../script\config\OpenSerConfig.lua
[7]="坐骑排行", 		--../script\config\OpenSerConfig.lua
[8]="法宝排行", 		--../script\config\OpenSerConfig.lua
[9]="最强世族", 		--../script\config\OpenSerConfig.lua
[10]="套装收集", 		--../script\config\OpenSerConfig.lua
[11]="境界奖励", 		--../script\config\OpenSerConfig.lua
[12]="限购商店", 		--../script\config\OpenSerConfig.lua
[13]="充值送豪礼", 		--../script\config\OpenSerConfig.lua
[14]="小有成就", 		--../script\config\OpenSerConfig.lua
[15]="斗战仙王", 		--../script\config\OpenSerConfig.lua
[16]="仙路漫漫兮", 		--../script\config\OpenSerConfig.lua
[17]="灵气修仙躯", 		--../script\config\OpenSerConfig.lua
[18]="名动天下", 		--../script\config\OpenSerConfig.lua
[19]="神兽相助", 		--../script\config\OpenSerConfig.lua
[20]="绚丽法宝", 		--../script\config\OpenSerConfig.lua
[21]="我们的家", 		--../script\config\OpenSerConfig.lua
[22]="靓丽套装", 		--../script\config\OpenSerConfig.lua
[23]="历尽天劫", 		--../script\config\OpenSerConfig.lua
[24]="限时大抢购", 		--../script\config\OpenSerConfig.lua
[25]="玩家在活动期间内，强化全身装备到达指定的等级，即可领取价值超额的礼包。", 		--../script\config\OperationActivityConfig.lua
[26]="玩家在活动期间内，宠物成长达到指定的要求，即可领取价值超额的礼包。", 		--../script\config\OperationActivityConfig.lua
[27]="玩家在活动期间内，法宝等级达到指定的要求，即可领取价值超额的礼包。", 		--../script\config\OperationActivityConfig.lua
[28]="玩家在活动期间内，每日登录，即可领取登录礼包，连续登录还可以领取额外的节日礼包", 		--../script\config\OperationActivityConfig.lua
[29]="玩家在活动期间内，充值累计达到指定的金额，即可领取超值大礼包", 		--../script\config\OperationActivityConfig.lua
[30]="玩家在活动期间内，消费累计达到888元宝，即可领取超值大礼包", 		--../script\config\OperationActivityConfig.lua
[31]="充值%s金额即可领取", 		--../script\config\OperationActivityConfig.lua
[32]="消费%s金额即可领取", 		--../script\config\OperationActivityConfig.lua
[33]="全身强化:", 		--../script\config\OperationActivityConfig.lua
[34]="成长等级:", 		--../script\config\OperationActivityConfig.lua
[35]="登录天数:", 		--../script\config\OperationActivityConfig.lua
[36]="已充值元宝:", 		--../script\config\OperationActivityConfig.lua
[37]="已消费元宝:", 		--../script\config\OperationActivityConfig.lua
[38]="云霄", 		--../script\control\GameLogicCC.lua
[39]="炎帝怨念", 		--../script\control\GameLogicCC.lua
[40]="的", 		--../script\control\GameLogicCC.lua
[41]="领取成功", 		--../script\control\OnlineAwardCC.lua
[42]="cdkey不存在", 		--../script\control\OnlineAwardCC.lua
[43]="cdkey已使用", 		--../script\control\OnlineAwardCC.lua
[44]="今天已经领取过礼包了", 		--../script\control\OnlineAwardCC.lua
[45]="下注成功", 		--../script\control\XianDaoHuiCC.lua
[46]="潇月", 		--../script\entity\EntityManager.lua
[47]="铜钱不足", 		--../script\entity\PlayerAvatar.lua
[48]="银两不足", 		--../script\entity\PlayerAvatar.lua
[49]="礼券不足", 		--../script\entity\PlayerAvatar.lua
[50]="关闭", 		--../script\GameStateManager.lua
[51]="您目前不是仙尊玩家", 		--../script\model\BagModel.lua
[52]="藏机", 		--../script\model\BagModel.lua
[53]="找到仓库管理员#r#cfff000仙尊玩家可以使用远程仓库功能", 		--../script\model\BagModel.lua
[54]="#c66ff66第%d名:#cffffff%s#r", 		--../script\model\BigActivityModel.lua
[55]="#c66ff66第4~6名:#r#cffffff%s", 		--../script\model\BigActivityModel.lua
[56]="#c66ff66第7~10名:#r#cffffff%s", 		--../script\model\BigActivityModel.lua
[57]="#c66FF66历练值获取方式 #r", 		--../script\model\ExchangeModel.lua
[58]="#c66FF661.通过挑战历练副本获得，击杀副本内怪物可获得历练值#r", 		--../script\model\ExchangeModel.lua
[59]="#c66FF662.开服前五天可通过充值活动获得500元宝礼包，礼包含有历练宝盒。#r", 		--../script\model\ExchangeModel.lua
[60]="#c66FF66荣誉值获取方式#r#c66FF661.通过1v1自由赛获得积分排名，根据排名获得荣誉值。#r#c66FF662.通过参加1v1争霸赛，获得荣誉值", 		--../script\model\ExchangeModel.lua
[61]="您的荣誉不足，无法兑换该道具", 		--../script\model\ExchangeModel.lua
[62]="您的历练不足，无法兑换该道具", 		--../script\model\ExchangeModel.lua
[63]="法宝晶石不足", 		--../script\model\FabaoModel.lua
[64]="白色和红色品质的仙魂无法放置到法宝仙魂槽中", 		--../script\model\FabaoModel.lua
[65]="#cffffff将吞噬", 		--../script\model\FabaoModel.lua
[66]="#cffffff,获得", 		--../script\model\FabaoModel.lua
[67]="经验", 		--../script\model\FabaoModel.lua
[68]="提升战斗力", 		--../script\model\GameSysModel.lua
[69]="召唤萱儿", 		--../script\model\GameSysModel.lua
[70]="演武场", 		--../script\model\GameSysModel.lua
[71]="首充礼包", 		--../script\model\GameSysModel.lua
[72]="领取翅膀", 		--../script\model\GameSysModel.lua
[73]="开服活动", 		--../script\model\GameSysModel.lua
[74]="欢乐斗", 		--../script\model\GameSysModel.lua
[75]="演武场排名", 		--../script\model\GameSysModel.lua
[76]="投资返利", 		--../script\model\GameSysModel.lua
[77]="仙侣情缘", 		--../script\model\GameSysModel.lua
[78]="签到", 		--../script\model\GameSysModel.lua
[79]="跑环", 		--../script\model\GameSysModel.lua
[80]="坐骑洗炼", 		--../script\model\GameSysModel.lua
[81]="法宝", 		--../script\model\GameSysModel.lua
[82]="法宝在43级开启", 		--../script\model\GameSysModel.lua
[83]="30级以上才能参加该活动。", 		--../script\model\Hyperlink.lua
[84]="该道具需要配合神秘百宝箱使用。", 		--../script\model\ItemModel.lua
[85]="族长", 		--../script\model\LeftClickMenuMgr.lua
[86]="副族长", 		--../script\model\LeftClickMenuMgr.lua
[87]="宗众", 		--../script\model\LeftClickMenuMgr.lua
[88]="求婚", 		--../script\model\LeftClickMenuMgr.lua
[89]="活动已经结束", 		--../script\model\LuopanModel.lua
[90]="同性不可以在一起!", 		--../script\model\MarriageModel.lua
[91]="您使用了一个坐骑洗炼符!", 		--../script\model\MountsModel.lua
[92]="是否消耗10个洗炼符洗炼10次?", 		--../script\model\MountsModel.lua
[93]="是否消耗%d个洗炼符%d元宝洗炼10次？", 		--../script\model\MountsModel.lua
[94]="是否消耗0个洗炼符和200元宝洗炼10次？", 		--../script\model\MountsModel.lua
[95]='获取服务器列表', 		--../script\model\RoleModel.lua
[96]="连接失败！[", 		--../script\model\RoleModel.lua
[97]="http失败!!!", 		--../script\model\RoleModel.lua
[98]="连接服务器失败！请您检查网络是否正常！[", 		--../script\model\RoleModel.lua
[99]='登录游戏', 		--../script\model\SelectServerRoleModel.lua
[100]="芊芊", 		--../script\model\ShopModel.lua
[101]="找到药品商店#r#cfff000仙尊玩家可以使用远程商店功能", 		--../script\model\ShopModel.lua
[102]="领取", 		--../script\model\TZFLModel.lua
[103]="已领取", 		--../script\model\TZFLModel.lua
[104]="元宝不足", 		--../script\model\WelfareModel.lua
[105]='重新连接服务器中', 		--../script\net\NetManager.lua
[106]="服务器忙蓝钻信息请求失败，蓝钻功能受影响，请按确定重试 error_code=", 		--../script\platform\QQVipInterface\QQBlueVipInterface.lua
[107]="#c7cfc00蓝钻", 		--../script\platform\QQVipInterface\QQBlueVipInterface.lua
[108]="无", 		--../script\struct\XDHUserStruct.lua
[109]='剩余内存[%.2fmb],可用内存[%.2fmb]', 		--../script\SystemInfo.lua
[110]="三个字", 		--../script\UI\activity\ActivityAwardPage.lua
[111]="副本内不能参加活动", 		--../script\UI\activity\ActivitySubWin.lua
[112]="#c66ff66(免费领取)", 		--../script\UI\activity\dailywelfare\DailyWelfareLD_exp.lua
[113]="#c66ff66(消耗#cffff00", 		--../script\UI\activity\dailywelfare\DailyWelfareLD_exp.lua
[114]="#c66ff66铜钱)", 		--../script\UI\activity\dailywelfare\DailyWelfareLD_exp.lua
[115]="#c66ff66元宝)", 		--../script\UI\activity\dailywelfare\DailyWelfareLD_exp.lua
[116]="#c66ff66(可获得灵气:#cffff00", 		--../script\UI\activity\dailywelfare\DailyWelfareLD_lq.lua
[117]="#c35c3f7(仙尊玩家领取双倍奖励)", 		--../script\UI\activity\dailywelfare\DailyWelfareLU.lua
[118]="增加", 		--../script\UI\activity\FubenActivityPage.lua
[119]="仓库", 		--../script\UI\bag\BagWin.lua
[120]="商店", 		--../script\UI\bag\BagWin.lua
[121]="寄售", 		--../script\UI\bag\BagWin.lua
[122]="整理", 		--../script\UI\bag\BagWin.lua
[123]="#c35C3F7规则说明:", 		--../script\UI\campBattle\CampBattleWin.lua
[124]="#c35C3F7战场时间:", 		--../script\UI\campBattle\CampBattleWin.lua
[125]="#c35C3F7活动奖励:", 		--../script\UI\campBattle\CampBattleWin.lua
[126]="参与媒体活动即可领取激活码", 		--../script\UI\codegift\CodeGiftWin.lua
[127]="#cffff00请输入激活码:", 		--../script\UI\codegift\code_gift_win_config.lua
[128]="确定", 		--../script\UI\common\SysMsgDialog.lua
[129]="再来一次", 		--../script\UI\common\SysMsgDialog.lua
[130]="立即传送", 		--../script\UI\common\SysMsgDialog.lua
[131]="取消", 		--../script\UI\common\SysMsgDialog.lua
[132]="#c33a6ee挑战倒计时:", 		--../script\UI\doufatai\DouFaTaiWin.lua
[133]="#c38ff33淘宝金币:", 		--../script\UI\dreamland\DreamlandWin.lua
[134]="#c38ff33优先使用淘宝金币", 		--../script\UI\dreamland\DreamlandWin.lua
[135]="     获取说明", 		--../script\UI\exchange\ExchangeWin.lua
[136]="#cfff000使用法宝晶石增加法宝经验", 		--../script\UI\fabao\FabaoUplevelWin.lua
[137]="请选择强化石材料", 		--../script\UI\forge\strengthenpage\StrengthenL.lua
[138]="背包", 		--../script\UI\forge\XiLianJiCheng.lua
[139]="确定放弃未替换的洗炼属性？", 		--../script\UI\forge\ZhiZunXiLianWin.lua
[140]="当前洗炼属性中有满属性值没有锁定，继续洗炼很有可能丢失该属性，确认继续洗炼吗？", 		--../script\UI\forge\ZhiZunXiLianWin.lua
[141]="新的洗炼属性中有满属性值没有替换，继续洗炼很有可能丢失该属性，确认继续洗炼吗？", 		--../script\UI\forge\ZhiZunXiLianWin.lua
[142]="#cfff000今日可免费洗炼", 		--../script\UI\forge\ZhuangBeiXiLian.lua
[143]="次", 		--../script\UI\forge\ZhuangBeiXiLian.lua
[144]="当前洗炼属性中有满属性值没有锁定，继续洗炼有可能丢失该属性，确认继续洗炼吗？", 		--../script\UI\forge\ZhuangBeiXiLian.lua
[145]="#cd5c241时间", 		--../script\UI\guild\GuildAltarEggPage.lua
[146]="#cd5c241事件", 		--../script\UI\guild\GuildAltarEggPage.lua
[147]="离线时间", 		--../script\UI\guild\GuildMember.lua
[148]="天", 		--../script\UI\guild\GuildMember.lua
[149]="小时", 		--../script\UI\guild\GuildMember.lua
[150]="购买", 		--../script\UI\guildshopwin\GuildShopWin.lua
[151]="全部", 		--../script\UI\JiShou\JiShouWin.lua
[152]="激活", 		--../script\UI\linggen\LingGen.lua
[153]="灵根名称", 		--../script\UI\linggen\LingGen.lua
[154]="属性:", 		--../script\UI\linggen\LingGen.lua
[155]="攻击 + 100", 		--../script\UI\linggen\LingGen.lua
[156]="#c00c0ff激活消耗灵气:", 		--../script\UI\linggen\LingGen.lua
[157]="#c00c0ff激活消耗银两:", 		--../script\UI\linggen\LingGen.lua
[158]="#cffffff灵根说明", 		--../script\UI\linggen\LingGen.lua
[159]="#c00c0ff点亮星辰，可提升人物属性", 		--../script\UI\linggen\LingGen.lua
[160]="#cffffff灵气获得", 		--../script\UI\linggen\LingGen.lua
[161]="#c00c0ff打坐双修、蟠桃盛宴、灵泉仙浴等。", 		--../script\UI\linggen\LingGen.lua
[162]="#cfff000灵气：", 		--../script\UI\linggen\LingGen.lua
[163]="重新开始", 		--../script\UI\llk\LlkGameWin.lua
[164]="服]", 		--../script\UI\login\NewSelectServerPage.lua
[165]="#cfff000温馨提示：系统默认只保留战斗力最强的6个角色", 		--../script\UI\login\SelectAliveRole.lua
[166]="#cff66cc可翻牌次数", 		--../script\UI\loginAward\LoginAwardWin.lua
[167]="#c03a1b0已连续登录2天", 		--../script\UI\loginAward\LoginAwardWin.lua
[168]="#c03a1b0累计已登录2天", 		--../script\UI\loginAward\LoginAwardWin.lua
[169]="#ca7a7a61.连续登录1天,可获得1次翻牌机会;", 		--../script\UI\loginAward\LoginAwardWin.lua
[170]="#ca7a7a62.连续登录2天,可获得2次翻牌机会;", 		--../script\UI\loginAward\LoginAwardWin.lua
[171]="#ca7a7a63.连续登录≥3天,可获得3次翻牌机会;", 		--../script\UI\loginAward\LoginAwardWin.lua
[172]="#ca7a7a64.如中途中断登录则重新开始计算。", 		--../script\UI\loginAward\LoginAwardWin.lua
[173]="#c00c0ff已连续登录", 		--../script\UI\loginAward\LoginAwardWin.lua
[174]="#c00c0ff累计已登录", 		--../script\UI\loginAward\LoginAwardWin.lua
[175]="是否使用20元宝抽奖？", 		--../script\UI\luopan\LuoPanPage.lua
[176]="跳过动画", 		--../script\UI\luopan\LuoPanWin.lua
[177]="每天登陆可免费领取一个幸运结晶;", 		--../script\UI\luopan\luo_pan_win_config.lua
[178]="幸运结晶可以抵消一次元宝消耗;", 		--../script\UI\luopan\luo_pan_win_config.lua
[179]="参与击杀精英怪活动可获得幸运结晶;", 		--../script\UI\luopan\luo_pan_win_config.lua
[180]="抽奖优先使用幸运结晶。", 		--../script\UI\luopan\luo_pan_win_config.lua
[181]="#cffff00幸运结晶:", 		--../script\UI\luopan\luo_pan_win_config.lua
[182]="#cffff00背包元宝:", 		--../script\UI\luopan\luo_pan_win_config.lua
[183]="#cfff00020元宝/次", 		--../script\UI\luopan\luo_pan_win_config.lua
[184]="#c66ff66发送:", 		--../script\UI\mail\ReadMailPage.lua
[185]="怒气值不足，不能释放", 		--../script\UI\main\MenusPanel.lua
[186]="正在打坐中,无法释放技能", 		--../script\UI\main\MenusPanel.lua
[187]="蓝量不足!", 		--../script\UI\main\MenusPanel.lua
[188]="技能cd中!", 		--../script\UI\main\MenusPanel.lua
[189]="是否离开副本?", 		--../script\UI\main\RightTopPanel.lua
[190]="此活动需要28级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[191]="此活动需要25级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[192]="此活动需要26级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[193]="此活动需要38级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[194]="此活动需要30级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[195]="此活动需要40级以上才可参加", 		--../script\UI\main\RightTopPanel.lua
[196]="您的宠物现在需要休息！", 		--../script\UI\main\UserPanel.lua
[197]="灵泉仙浴中宠物不能出战", 		--../script\UI\main\UserPanel.lua
[198]="背包中没有药品，不能自动加血，您可以:返回天元城找#cffff00芊芊#cffffff购买药品。(#cffff00仙尊用户可以快捷打开商店#cffffff)", 		--../script\UI\main\UserPanel.lua
[199]="背包中没有药品，不能自动加法力，您可以:返回天元城找#cffff00芊芊#cffffff购买药品。(#cffff00仙尊用户可以快捷打开商店#cffffff)", 		--../script\UI\main\UserPanel.lua
[200]="背包已没有药品，宠物不能自动加血，您可以:返回天元城找#cffff00芊芊#cffffff购买药品。(#cffff00仙尊用户可以快捷打开商店#cffffff)", 		--../script\UI\main\UserPanel.lua
[201]="您的宠物被杀死了，20秒后才能再次出战", 		--../script\UI\main\UserPanel.lua
[202]="背包中没有拨浪鼓了，不能提高宠物快乐度，您可以:返回天元城找#cffff00芊芊#cffffff购买拨浪鼓。(#cffff00仙尊用户可以快捷打开商店#cffffff)", 		--../script\UI\main\UserPanel.lua
[203]="冷却时间未结束", 		--../script\UI\marriage\MarriagePlayWin.lua
[204]="您的婚戒已经升到最高级!", 		--../script\UI\marriage\MarriageUpRingPage.lua
[205]="您的情意值不足，不能升级戒指!", 		--../script\UI\marriage\MarriageUpRingPage.lua
[206]="#cff66cc当前情意: #cffffff", 		--../script\UI\marriage\MarriageUpRingPage.lua
[207]="#cfff000需要情意: #cffffff", 		--../script\UI\marriage\MarriageUpRingPage.lua
[208]="更换不同的外观，不会影响属性", 		--../script\UI\mounts\MountsHuaXingWin.lua
[209]="需要坐骑等级15级才能开启洗炼！", 		--../script\UI\mounts\MountsInfoWin.lua
[210]="洗炼", 		--../script\UI\mounts\MountsInfoWin.lua
[211]="需要坐骑等级45级才能开启洗练！", 		--../script\UI\mounts\MountsWin.lua
[212]="#c33a6ee生    命 :", 		--../script\UI\mounts\MountsWin.lua
[213]="#c33a6ee法术防御 :", 		--../script\UI\mounts\MountsWin.lua
[214]="#c33a6ee暴    击 :", 		--../script\UI\mounts\MountsWin.lua
[215]="#c33a6ee攻    击 :", 		--../script\UI\mounts\MountsWin.lua
[216]="#c33a6ee外功防御 :", 		--../script\UI\mounts\MountsWin.lua
[217]="#c33a6ee移动速度 :", 		--../script\UI\mounts\MountsWin.lua
[218]="1万", 		--../script\UI\mounts\MountsXiLianWin.lua
[219]="外功防御", 		--../script\UI\mounts\MountsXiLianWin.lua
[220]="灵气", 		--../script\UI\mounts\MountsXiLianWin.lua
[221]="攻击", 		--../script\UI\mounts\MountsXiLianWin.lua
[222]="法术防御", 		--../script\UI\mounts\MountsXiLianWin.lua
[223]="铜钱", 		--../script\UI\mounts\MountsXiLianWin.lua
[224]="生命", 		--../script\UI\mounts\MountsXiLianWin.lua
[225]="绑定元宝", 		--../script\UI\mounts\MountsXiLianWin.lua
[226]="暴击", 		--../script\UI\mounts\MountsXiLianWin.lua
[227]="银两", 		--../script\UI\mounts\MountsXiLianWin.lua
[228]="铜钱洗炼", 		--../script\UI\mounts\MountsXiLianWin.lua
[229]="#cd5c24130000铜钱", 		--../script\UI\mounts\MountsXiLianWin.lua
[230]="元宝洗炼", 		--../script\UI\mounts\MountsXiLianWin.lua
[231]="#cd5c24120元宝(双倍收益)", 		--../script\UI\mounts\MountsXiLianWin.lua
[232]="批量洗炼", 		--../script\UI\mounts\MountsXiLianWin.lua
[233]="#cd5c241200元宝", 		--../script\UI\mounts\MountsXiLianWin.lua
[234]="资质已达上限", 		--../script\UI\mounts\MountsXiLianWin.lua
[235]="使用神秘钥匙开启有更高的几率获得更多稀有道具,是否消耗1把神秘钥匙开启?", 		--../script\UI\openbox\OpenBoxDialog.lua
[236]="#c66ff66神秘钥匙:9999", 		--../script\UI\openbox\OpenBoxWin.lua
[237]="#c66ff66神秘百宝箱:9999", 		--../script\UI\openbox\OpenBoxWin.lua
[238]="道具", 		--../script\UI\openbox\OpenBoxWin.lua
[239]="#c66ff66神秘礼包:", 		--../script\UI\openbox\OpenBoxWin.lua
[240]="#c66ff66神秘钥匙:", 		--../script\UI\openbox\OpenBoxWin.lua
[241]="#c66ff66神秘百宝箱:", 		--../script\UI\openbox\OpenBoxWin.lua
[242]="获得%s x %d", 		--../script\UI\openbox\OpenBoxWin.lua
[243]="#c66ff66登录天数:#cffffff", 		--../script\UI\operateActivity\BigActivityWin.lua
[244]="#c66ff66充值元宝:#cffffff", 		--../script\UI\operateActivity\BigActivityWin.lua
[245]="#c66ff66消费元宝:#cffffff", 		--../script\UI\operateActivity\BigActivityWin.lua
[246]="#c66ff66充值元宝#cffffff", 		--../script\UI\operateActivity\BigActivityWin.lua
[247]="#c66ff66消费元宝#cffffff", 		--../script\UI\operateActivity\BigActivityWin.lua
[248]="#c38ff33活动时间:", 		--../script\UI\operateActivity\BigActivityWin.lua
[249]="#c38ff33活动说明:", 		--../script\UI\operateActivity\BigActivityWin.lua
[250]="#c38ff33剩余时间:", 		--../script\UI\operateActivity\BigActivityWin.lua
[251]="名单将在活动结束后发布", 		--../script\UI\operateActivity\BigActivityWin.lua
[252]="领取索引有错", 		--../script\UI\operateActivity\BigActivityWin.lua
[253]="活动已截止，请尽快领取所得奖励", 		--../script\UI\operateActivity\BigActivityWin.lua
[254]="任意金额", 		--../script\UI\operateActivity\SmallOperationActivityCell.lua
[255]="888元宝", 		--../script\UI\operateActivity\SmallOperationActivityCell.lua
[256]="资质      当前等级  下个等级", 		--../script\UI\pet\PetChengZhangPage.lua
[257]="说明", 		--../script\UI\pet\PetChengZhangPage.lua
[258]="使用保护珠", 		--../script\UI\pet\PetChengZhangPage.lua
[259]="#c66ff66提升失败成长-1", 		--../script\UI\pet\PetChengZhangPage.lua
[260]="#c66ff66提升失败等级不变", 		--../script\UI\pet\PetChengZhangPage.lua
[261]="悟    性:", 		--../script\UI\pet\PetOpenEggWin.lua
[262]="成    长:", 		--../script\UI\pet\PetOpenEggWin.lua
[263]="攻击资质:", 		--../script\UI\pet\PetOpenEggWin.lua
[264]="防御资质:", 		--../script\UI\pet\PetOpenEggWin.lua
[265]="灵巧资质:", 		--../script\UI\pet\PetOpenEggWin.lua
[266]="身法资质:", 		--../script\UI\pet\PetOpenEggWin.lua
[267]="#c66ff66战斗力:", 		--../script\UI\pet\PetWin.lua
[268]="攻    击:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[269]="外功防御:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[270]="法术防御:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[271]="暴    击:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[272]="命    中:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[273]="闪    避:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[274]="抗 暴 击:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[275]="生    命:#cffff00", 		--../script\UI\pet\PetWuXingPage.lua
[276]="#c66ff66攻    击:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[277]="#c66ff66外功防御:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[278]="#c66ff66法术防御:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[279]="#c66ff66暴    击:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[280]="#c66ff66命    中:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[281]="#c66ff66闪    避:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[282]="#c66ff66抗 暴 击:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[283]="#c66ff66生    命:#cffffff", 		--../script\UI\pet\PetWuXingPage.lua
[284]="#c66ff66提升失败悟性-1", 		--../script\UI\pet\PetWuXingPage.lua
[285]="苏醒记忆", 		--../script\UI\pet\SuXingWin.lua
[286]="第", 		--../script\UI\pushBox\PushBoxWin.lua
[287]="关", 		--../script\UI\pushBox\PushBoxWin.lua
[288]="上一关", 		--../script\UI\pushBox\PushBoxWin.lua
[289]="下一关", 		--../script\UI\pushBox\PushBoxWin.lua
[290]="蓝钻用户可免费领取蓝钻专属宠物：卓越- 布鲁娃娃", 		--../script\UI\qqvip\QQVIPAward.lua
[291]="蓝钻用户在角色名前方显示尊贵的蓝钻个性标识", 		--../script\UI\qqvip\QQVIPAward.lua
[292]="蓝钻用户在商城购物可享受8折优惠", 		--../script\UI\qqvip\QQVIPAward.lua
[293]="蓝钻用户可每日领取丰厚的礼包奖励", 		--../script\UI\qqvip\QQVIPAward.lua
[294]="#cd5c241卓越·布鲁娃娃", 		--../script\UI\qqvip\QQVIPAward.lua
[295]="您目前总分数：", 		--../script\UI\questionactivity\QuestionActivityWin.lua
[296]="您目前的排名：", 		--../script\UI\questionactivity\QuestionActivityWin.lua
[297]="您答对的题目：", 		--../script\UI\questionactivity\QuestionActivityWin.lua
[298]="您答错的题目：", 		--../script\UI\questionactivity\QuestionActivityWin.lua
[299]="1、新增世界时间", 		--../script\UI\secretary\notice_page_config.lua
[300]="2、商城热销区新增每日限购宝箱", 		--../script\UI\secretary\notice_page_config.lua
[301]="3、商城热销区新增神秘钥匙道具", 		--../script\UI\secretary\notice_page_config.lua
[302]="4、诛仙阵掉落修改为神秘百宝箱", 		--../script\UI\secretary\notice_page_config.lua
[303]="1、世族贡献显示成员的累积贡献", 		--../script\UI\secretary\notice_page_config.lua
[304]="2、法宝改为角色达到43级直接开启", 		--../script\UI\secretary\notice_page_config.lua
[305]="3、跑环任务50级前取消天劫石任务", 		--../script\UI\secretary\notice_page_config.lua
[306]="4、新版UI，可以伸缩隐藏功能面板", 		--../script\UI\secretary\notice_page_config.lua
[307]="领取离线经验", 		--../script\UI\secretary\secretaryrow\ExpSR.lua
[308]="#c33a6ee累计登陆天数满足条件可以获取丰厚礼包！最高可获取价值", 		--../script\UI\sevenDayAward\sevenDayAward.lua
[309]="#c33a6ee的礼包", 		--../script\UI\sevenDayAward\sevenDayAward.lua
[310]="回购", 		--../script\UI\shop\ShopSellPanel.lua
[311]="双修", 		--../script\UI\shuangxiu\XunRenShuangXiuWin.lua
[312]="#cfff000姓名", 		--../script\UI\shuangxiu\YQSXWin.lua
[313]="#cfff000等级", 		--../script\UI\shuangxiu\YQSXWin.lua
[314]="#cfff000性别", 		--../script\UI\shuangxiu\YQSXWin.lua
[315]="接受", 		--../script\UI\shuangxiu\YQSXWin.lua
[316]="拒绝", 		--../script\UI\shuangxiu\YQSXWin.lua
[317]="点击兑换", 		--../script\UI\task\NPCDialog.lua
[318]="历练副本", 		--../script\UI\task\NPCDialog.lua
[319]="诛仙阵", 		--../script\UI\task\NPCDialog.lua
[320]="宠物岛", 		--../script\UI\task\NPCDialog.lua
[321]="#c33a6ee任务目标: ", 		--../script\UI\task\ZYCMWin.lua
[322]="还未开始计时", 		--../script\UI\tips\DressTipView.lua
[323]="使用时间:", 		--../script\UI\tips\DressTipView.lua
[324]="%Y年%m月%d日 %H时%M分", 		--../script\UI\tips\FootEffectTipView.lua
[325]="到期时间：#r", 		--../script\UI\tips\FootEffectTipView.lua
[326]="基础属性:", 		--../script\UI\tips\FootEffectTipView.lua
[327]="未绑定", 		--../script\UI\tips\FootEffectTipView.lua
[328]="已绑定", 		--../script\UI\tips\FootEffectTipView.lua
[329]="需要等级： ", 		--../script\UI\tips\FootEffectTipView.lua
[330]="使用时间: 永久", 		--../script\UI\tips\FootEffectTipView.lua
[331]="#c36ff33需要:  #cffffff亲密度", 		--../script\UI\tips\MarriageHeartTipView.lua
[332]="御灵镜幻", 		--../script\UI\tips\WingSkillTipView.lua
[333]="真武玄盾", 		--../script\UI\tips\WingSkillTipView.lua
[334]="万", 		--../script\UI\tongji\ZhengBaSaiView.lua
[335]="#cfff000名称", 		--../script\UI\tongji\ZhengBaSaiView.lua
[336]="#cfff000身价", 		--../script\UI\tongji\ZhengBaSaiView.lua
[337]="六个字的名字", 		--../script\UI\tongji\ZhengBaSaiView.lua
[338]="名    次:", 		--../script\UI\tongji\ZiYouSaiView.lua
[339]="积    分:", 		--../script\UI\tongji\ZiYouSaiView.lua
[340]="比赛次数:", 		--../script\UI\tongji\ZiYouSaiView.lua
[341]="胜利次数:", 		--../script\UI\tongji\ZiYouSaiView.lua
[342]="胜    率:", 		--../script\UI\tongji\ZiYouSaiView.lua
[343]="荣    誉:", 		--../script\UI\tongji\ZiYouSaiView.lua
[344]="#cfff000我的自由赛信息", 		--../script\UI\tongji\ZiYouSaiView.lua
[345]="#c66ff66名次每分钟刷新一次", 		--../script\UI\tongji\ZiYouSaiView.lua
[346]='#c00ff00修复游戏', 		--../script\UI\UI_Utilities.lua
[347]='#cffff00当您无法正常登录或进行游戏时', 		--../script\UI\UI_Utilities.lua
[348]='#cffff00请尝试修复游戏，还原到原始版本', 		--../script\UI\UI_Utilities.lua
[349]='#cffff00还原完成需重新启动游戏', 		--../script\UI\UI_Utilities.lua
[350]='#cffff00重新更新后即可修复问题', 		--../script\UI\UI_Utilities.lua
[351]='取消', 		--../script\UI\UI_Utilities.lua
[352]='退出', 		--../script\UI\UI_Utilities.lua
[353]='修复', 		--../script\UI\UI_Utilities.lua
[354]='连接中断', 		--../script\UI\UI_Utilities.lua
[355]='与服务器失去连接，请检看你的网络', 		--../script\UI\UI_Utilities.lua
[356]='连接后再次连接。', 		--../script\UI\UI_Utilities.lua
[357]="#cffffcf请重试", 		--../script\UI\UI_Utilities.lua
[358]="#c33a6ee您当前的级别:", 		--../script\UI\VIP\VIPSysWin.lua
[359]="#cfff000裙子女孩#c38ff33,您还不是仙尊玩家。", 		--../script\UI\VIP\VIPSysWin.lua
[360]="#c38ff33,您还不是仙尊用户。", 		--../script\UI\VIP\VIPSysWin.lua
[361]="#c38ff33√", 		--../script\UI\VIP\VIPSysWin.lua
[362]="#cfff000√", 		--../script\UI\VIP\VIPSysWin.lua
[363]="当前是第一页", 		--../script\UI\wing\WingSysWin.lua
[364]="当前是最后一页", 		--../script\UI\wing\WingSysWin.lua
[365]="争霸赛场景内才能下注", 		--../script\UI\xiandaohui\BJZBS.lua
[366]="荣      誉：", 		--../script\UI\xiandaohui\BJZYS.lua
[367]="兑换", 		--../script\UI\xiandaohui\BJZYS.lua
[368]="排名", 		--../script\UI\xiandaohui\BJZYS.lua
[369]="姓名", 		--../script\UI\xiandaohui\BJZYS.lua
[370]="阵营", 		--../script\UI\xiandaohui\BJZYS.lua
[371]="积分", 		--../script\UI\xiandaohui\BJZYS.lua
[372]="战力", 		--../script\UI\xiandaohui\BJZYS.lua
[373]="胜率", 		--../script\UI\xiandaohui\BJZYS.lua
[374]="#c35c3f7排行榜数据每分钟更新", 		--../script\UI\xiandaohui\BJZYS.lua
[375]="名      次：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[376]="积      分：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[377]="积累比赛：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[378]="积累胜利：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[379]="胜      率：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[380]="荣      誉：#cfff000", 		--../script\UI\xiandaohui\BJZYS.lua
[381]="序号", 		--../script\UI\xiandaohui\LJXW.lua
[382]="世族", 		--../script\UI\xiandaohui\LJXW.lua
[383]="宠物战力", 		--../script\UI\xiandaohui\LJXW.lua
[384]="时间", 		--../script\UI\xiandaohui\LJXW.lua
[385]="第%d届", 		--../script\UI\xiandaohui\LJXW.lua
[386]="战    力:", 		--../script\UI\xiandaohui\ResultDialog.lua
[387]="#c35c3f7后离开", 		--../script\UI\xiandaohui\ResultDialog.lua
[388]="比赛场次", 		--../script\UI\xiandaohui\SJSLQ.lua
[389]="仙道宝盒已用完", 		--../script\UI\xiandaohui\XianDaoBaoHeWin.lua
[390]="使用黄金手能让您获得珍贵道具的概率更大哦！", 		--../script\UI\xiandaohui\XianDaoBaoHeWin.lua
[391]="仙道宝盒使用中，请耐心等待。", 		--../script\UI\xiandaohui\XianDaoBaoHeWin.lua
[392]="战      力:", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[393]="身      价:", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[394]="需要铜钱:", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[395]="#u1#c35c3f7寻路#u0", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[396]="一", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[397]="二", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[398]="三", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[399]="四", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[400]="五", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[401]="比赛将于%s在第%s擂台举行", 		--../script\UI\xiandaohui\XiaZhuDialog.lua
[402]="只能对十六强玩家使用", 		--../script\UI\xiandaohui\ZBSActionWin.lua
[403]="送飞吻冷却时间未结束", 		--../script\UI\xiandaohui\ZBSActionWin.lua
[404]="扔鸡蛋冷却时间未结束", 		--../script\UI\xiandaohui\ZBSActionWin.lua
[405]="争霸赛已经结束", 		--../script\UI\xiandaohui\ZBSActionWin.lua
[406]="%s次", 		--../script\UI\xiandaohui\ZBSActionWin.lua
[407]="围观", 		--../script\UI\xiandaohui\ZBSJC.lua
[408]="比赛状态:#cfff000比赛中", 		--../script\UI\xiandaohui\ZBSJC.lua
[409]="比赛状态:#cfff000", 		--../script\UI\xiandaohui\ZBSJC.lua
[410]="胜利，晋级八强", 		--../script\UI\xiandaohui\ZBSJC.lua
[411]="胜利，晋级四强", 		--../script\UI\xiandaohui\ZBSJC.lua
[412]="胜利，晋级决赛", 		--../script\UI\xiandaohui\ZBSJC.lua
[413]="胜利，获得冠军", 		--../script\UI\xiandaohui\ZBSJC.lua
[414]="#c35c3f7十六强争霸赛第二轮将于 #cfff000", 		--../script\UI\xiandaohui\ZBSJC.lua
[415]=" #c35c3f7开始", 		--../script\UI\xiandaohui\ZBSJC.lua
[416]=" #c35c3f7结束", 		--../script\UI\xiandaohui\ZBSJC.lua
[417]="#c35c3f7八强争霸赛将于 #cfff000", 		--../script\UI\xiandaohui\ZBSJC.lua
[418]="#c35c3f7四强将于 #cfff000", 		--../script\UI\xiandaohui\ZBSJC.lua
[419]="#c35c3f7决赛将于 #cfff000", 		--../script\UI\xiandaohui\ZBSJC.lua
[420]='正在初始化', 		--../script\UpdateManager.lua
[421]='#cffff00错误码:[', 		--../script\UpdateManager.lua
[422]="月", 		--../script\utils\Utils.lua
[423]="日", 		--../script\utils\Utils.lua
[424]="级领取", 		--../script\XSZY\XSZYManager.lua
}
